run:
  concurrency: 4
  timeout: 3m
  tests: false

linters:
  presets:
    - bugs
    - comment
    - error
    - import
    - metalinter
    - module
    - performance
    - sql
    - unused
  disable:
    - depguard
    - gci
    - perfsprint
